apiVersion: v1
kind: Service
metadata:
  name: "{{ template "mentorme.fullname" . }}-backend"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "mentorme.fullname" . }}-backend"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations: {}
spec:
  type: {{ .Values.backend.service.type }}
  {{- if (and (eq .Values.backend.service.type "LoadBalancer") (not (empty .Values.backend.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mentorme-backend
    port: 80
    targetPort: backend
    {{- if .Values.backend.service.nodePort }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  selector:
    app: "{{ template "mentorme.fullname" . }}-backend"
