apiVersion: v1
kind: Service
metadata:
  name: "{{ template "mentorme.fullname" . }}-frontend"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "mentorme.fullname" . }}-frontend"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations: {}

spec:
  type: {{ .Values.frontend.service.type }}
  {{- if (and (eq .Values.frontend.service.type "LoadBalancer") (not (empty .Values.frontend.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mentorme-frontend
    # TODO change the service port in values.yaml
    port: 80
    targetPort: frontend
    {{- if .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  selector:
    app: "{{ template "mentorme.fullname" . }}-frontend"
