apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mentorme-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: mentorme{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: "{{ template "mentorme.fullname" . }}-backend"
          servicePort: 80
        path: /api(/|$)(.*)
      - backend:
          serviceName: "{{ template "mentorme.fullname" . }}-frontend"
          servicePort: 80
        path: /(.*)
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mentorme-frontend-static-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: mentorme{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: "{{ template "mentorme.fullname" . }}-frontend"
          servicePort: 80
        path: /static(/|$)(.*)

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mentorme-backend-admin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /admin/$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: mentorme{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: "{{ template "mentorme.fullname" . }}-backend"
          servicePort: 80
        path: /admin(/|$)(.*)