# Generated by Django 3.0.3 on 2020-02-13 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], max_length=10)),
                ('mentee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_rel', to=settings.AUTH_USER_MODEL)),
                ('mentor_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mentee_user_id', 'mentor_user_id')},
            },
        ),
    ]
