# Generated by Django 3.0.3 on 2020-02-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_available_date'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='mentee_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_rel', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='mentor_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rel', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], max_length=10, null=True),
        ),
    ]
