# Generated by Django 3.0.3 on 2020-02-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_auto_20200213_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='mentee_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='mentor_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
