# Generated by Django 3.0.3 on 2020-02-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_available_date'),
        ('matching', '0004_auto_20200213_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='mentee_user_id',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='mentor_user_id',
            new_name='mentor',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('mentee', 'mentor')},
        ),
    ]
