# Generated by Django 3.0.3 on 2020-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200209_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_date',
            field=models.TextField(default='MON,TUE,WED,THU,FRI,SAT,SUN', max_length=100),
        ),
    ]
