# Generated by Django 3.0.3 on 2020-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200309_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='', max_length=200),
        ),
    ]
